# Handle git submodules yourself
git:
    submodules: false

language: cpp

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
      - valgrind

env:

  global:

  jobs:
    - CONFIG=Debug
    - CONFIG=Release

# Use sed to replace the SSH URL with the public URL, then initialize submodules
before_install:
  - set -e
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive

install:

before_script:
  - sudo apt-get -qq update
  - sudo apt-get install -y libx11-xcb-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev

script:
  - ./build.sh

jobs:

after_success:
  - bash <(curl -s https://codecov.io/bash)