# Syntax reference https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions
# Environment reference https://help.github.com/en/actions/reference/virtual-environments-for-github-hosted-runners
name: Coverage

on: ["push", "pull_request"]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install missing software on ubuntu
        run: |
          sudo apt-get update
          sudo apt-get install libxml2-utils
          sudo apt-get install z3 libz3-dev
          sudo apt-get install lcov
          sudo apt-get -qq update
          sudo apt-get install -y libx11-xcb-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev
          pip install lcov_cobertura

      - name: Compile instrumented
        run: |
          cmake --build build CXXFLAGS="-g -fprofile-arcs -ftest-coverage" -j$(nproc)
          
      - name: Generate coverage report
        run: |
          rm -rf coverage_report
          ./testrunner
          lcov --directory ./ --capture --output-file lcov_tmp.info -b ./
          lcov --extract lcov_tmp.info "$(pwd)/*" --output-file lcov.info
          genhtml lcov.info -o coverage_report --frame --legend --demangle-cpp
          
      - uses: actions/upload-artifact@v1
        with:
         name: Coverage results
         path: coverage_report
         
      - uses: codecov/codecov-action@v1
        with:
          # token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          # file: ./coverage.xml # optional
          flags: unittests # optional
          name: ${{ github.repository }} # optional
          fail_ci_if_error: true # optional (default = false):  